use std::{time::Instant, cell::RefCell, collections::HashMap};
use serde::{Serialize, Deserialize};
mod component_storage;
use slotmap::{SecondaryMap, SlotMap};
pub use component_storage::*;
mod component;
pub use component::*;
mod id;
pub use id::*;
mod world;
pub use world::*;
mod entity;
pub use entity::*;
mod singleton;
pub use singleton::*;
pub mod singleton_storage;
pub use singleton_storage::*;